name: PR Check Commit Chart.yaml

on:
  pull_request:
    paths:
      - '*'
      - '!.github/workflows/**'
      

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Get changed files
        id: changed-files-yaml
        uses: tj-actions/changed-files@v40
        with:
          files_yaml: |
            chart:
              - Chart.yaml

      - name: Run step only when any of the above files change.
        if: steps.changed-files-yaml.outputs.chart == 'false'  
        run: |
          echo "Please commit: ${{ steps.verify-changed-files.outputs.chart }}"
        # Outputs: "Changed files: new.txt test_directory/new.txt"

