name: PR Check Commit Chart.yaml

on:
  pull_request:
    paths:
      - '*'
      - '!.github/workflows/**'
      

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40
      - name: Check commit Chart.yaml
        run: |
          touch change.txt
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file" >> change.txt
          done
          grep Chart.yaml change.txt && echo "Nice Job" || echo "Please commit Chart.yaml" && exit 1 