name: Release Helm Charts

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  release_helm_chart:
    name: Releases Helm Chart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: install helm cli
        id: install
        uses: azure/setup-helm@v3.5
        with:
          version: 'v3.13.1' # default is latest (stable)
          #token: ${{ secrets.GITHUB_TOKEN }} # only needed if version is 'latest'

      - name: Add dependency helm chart repo
        env:
          AWS_S3: ${{ secrets.AWS_S3 }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          helm version
          helm plugin install https://github.com/hypnoglow/helm-s3.git --version 0.15.1
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add helm-demo ${AWS_S3}

      - name: Release helm chart
        env:
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          export TAG=${GITHUB_REF#refs/*/}
          export VERSION=$(echo $TAG | cut -d 'v' -f 2)
          export CHECK_CHART_VERSION=$(cat Chart.yaml | grep '^version: ' | cut -d ' ' -f 2)
          echo "TAG=$TAG"
          echo "VERSION=$VERSION"
          echo "CHECK_CHART_VERSION=$CHECK_CHART_VERSION"
          [[ $VERSION != $CHECK_CHART_VERSION ]] && exit 1 || echo "check ok"
          helm dependency update
          helm package .
          helm s3 push ./helm-demo-$VERSION.tgz helm-demo 
  release_github:
    name: Publish to GitHub Releases
    needs: release_helm_chart
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          export VERSION=$(cat Chart.yaml | grep '^version: ' | cut -d ' ' -f 2)
          gh release create v${VERSION} --generate-notes --repo $GITHUB_REPOSITORY
